# EMQX 5 基础配置

node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

cluster {
  name = emqxcl
  discovery_strategy = manual
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}

listeners.ssl.default {
  bind = "0.0.0.0:8883"
  max_connections = 512000
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
  max_connections = 1024000
}

listeners.wss.default {
  bind = "0.0.0.0:8084"
  max_connections = 512000
}

dashboard {
  listeners.http.bind = "0.0.0.0:18083"
  default_username = "admin"
  default_password = "admin123456"
}

# 日志配置
log {
  file {
    enable = true
    level = info
    path = "log/emqx.log"
    rotation_size = 10MB
    rotation_count = 5
  }
  console {
    enable = true
    level = info
  }
}
