appname = nps
#Boot mode(dev|pro)
runmode = dev

#HTTP(S) proxy port, no startup if empty
http_proxy_ip=0.0.0.0
http_proxy_port=80
https_proxy_port=443
https_just_proxy=true
#default https certificate setting
https_default_cert_file=conf/server.pem
https_default_key_file=conf/server.key

##bridge
bridge_type=tcp
bridge_port=8024
bridge_ip=0.0.0.0

#Public password, which clients can use to connect to the server
public_vkey=12345678

#Traffic data persistence interval(minute)
#Ignorance means no persistence
#flow_store_interval=1

# log level
log_level=info

#Web management
web_host=0.0.0.0
web_username=admin
web_password=admin123456
web_port=8080
web_ip=0.0.0.0

#allow Ports
allow_ports=9001-9999

#Web API unauthenticated IP address(the len of auth_key is 0 or 8)
#auth_key=test
auth_crypt_key =1234567812345678
