auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

schema_config:
  configs:
    - from: 2024-01-01
      store: loki
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb:
    directory: /loki/boltdb-ship
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  retention_period: 168h
  max_global_streams_per_user: 0

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  poll_interval: 2m

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_timeout: 5m
