version: '3.8'

services:
  debian:
    image: debian:bookworm-slim
    container_name: debian
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    command: tail -f /dev/null
    volumes:
      - debian_home:/root
      - ./data:/data
    networks:
      - debian_network

volumes:
  debian_home:
    driver: local

networks:
  debian_network:
    driver: bridge
